#!/usr/bin/env python3
"""Turn the tinted-theming scheme library into `themes/base16.toml`.

The schemes are sixteen colours each and nothing else; what those sixteen
mean for an editor is `themes/base16-template.toml`, which is written by
hand and read at runtime. This only carries the palettes across, so that
refreshing the library is a command rather than an afternoon.

    themes/import-base16.py ~/src/tinted-theming-schemes

The argument is a checkout of https://github.com/tinted-theming/schemes,
or the directory its `base16/` sits in. With no argument it fetches the
tarball itself, which wants network.
"""

import pathlib
import re
import subprocess
import sys
import tempfile

TARBALL = "https://github.com/tinted-theming/schemes/archive/refs/heads/spec-0.11.tar.gz"

# `base00: "#1d2021" # ----`, and the three lines above the palette. The
# files are YAML, but the shape is fixed enough that a regex beats a
# dependency: one key per line, one flat map, no anchors or blocks.
FIELD = re.compile(r'^(\w+):\s*"?(.*?)"?\s*$')
COLOUR = re.compile(r'^\s+(base[0-9A-F]{2}):\s*"?(#[0-9a-fA-F]{6})"?')


def scheme(path):
    """One scheme file as (slug, name, author, variant, sixteen colours)."""
    head, palette = {}, {}
    for line in path.read_text().splitlines():
        if colour := COLOUR.match(line):
            palette[colour.group(1)] = colour.group(2)
        elif field := FIELD.match(line):
            head[field.group(1)] = field.group(2)
    wanted = [f"base{n:02X}" for n in range(16)]
    if any(key not in palette for key in wanted):
        return None
    return {
        "slug": path.stem,
        "name": head.get("name", path.stem),
        "author": head.get("author", ""),
        "variant": head.get("variant", "dark"),
        "palette": [palette[key] for key in wanted],
    }


def quote(text):
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) > 1:
        root = pathlib.Path(sys.argv[1])
    else:
        root = pathlib.Path(tempfile.mkdtemp())
        subprocess.run(f"curl -sSL {TARBALL} | tar xz -C {root}", shell=True, check=True)
        root = next(root.glob("schemes-*"))
    folder = root if (root / "base00.yaml").exists() else root / "base16"
    if not folder.is_dir():
        sys.exit(f"no base16/ under {root}")

    schemes = sorted(filter(None, (scheme(p) for p in sorted(folder.glob("*.yaml")))),
                     key=lambda s: s["slug"])
    out = [
        "# The tinted-theming scheme library, palettes only: sixteen colours",
        "# and who chose them. What the sixteen mean is base16-template.toml.",
        "#",
        "# Generated by themes/import-base16.py - do not edit by hand.",
        "# MIT, and the licence is beside this file as BASE16-LICENSE.",
        "",
    ]
    for s in schemes:
        out.append(f'[{quote(s["slug"])}]')
        out.append(f'name = {quote(s["name"])}')
        out.append(f'variant = {quote(s["variant"])}')
        if s["author"]:
            out.append(f'author = {quote(s["author"])}')
        out.append("palette = [%s]" % ", ".join(quote(c) for c in s["palette"]))
        out.append("")

    here = pathlib.Path(__file__).resolve().parent
    (here / "base16.toml").write_text("\n".join(out))
    licence = root / "LICENSE"
    if licence.exists():
        (here / "BASE16-LICENSE").write_text(licence.read_text())
    print(f"{len(schemes)} schemes into {here / 'base16.toml'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
