#!/usr/bin/env bash
# Print the Homebrew formula for a released version, with the checksums of the
# tarballs that release actually contains.
#
# Usage: render-formula.sh <version> <directory of .sha256 files>
#        render-formula.sh --source <version>          (builds on the user's
#                                                       machine instead)
#
# The release workflow runs this and attaches the result to the release, so
# updating the tap is copying one file into it. Run it by hand the same way:
#   gh release download v0.1.0 --pattern '*.sha256' --dir sums
#   ./packaging/homebrew/render-formula.sh 0.1.0 sums > ../homebrew-tap/Formula/jack.rb
set -euo pipefail

repo=${JACK_REPO:-rgsoda/jack-editor}

# `--source <version>` prints the other kind of formula: one that builds from
# the source tarball with the tap user's own toolchain. Slower to install and
# it needs Rust and a C compiler on their machine, but it depends on nothing
# but the tag - useful before the release workflow has run, or if a target
# fails to build. The checksum is fetched rather than left to be pasted in.
if [ "${1:-}" = "--source" ]; then
    version=${2:?usage: render-formula.sh --source <version>}
    tarball="https://github.com/$repo/archive/refs/tags/v$version.tar.gz"
    sha=$(curl -sSfL "$tarball" | shasum -a 256 | cut -d' ' -f1)
    cat <<FORMULA
# Generated by packaging/homebrew/render-formula.sh --source $version.
class Jack < Formula
  desc "Terminal text editor with tree-sitter highlighting and vim keys"
  homepage "https://github.com/$repo"
  url "$tarball"
  sha256 "$sha"
  license "MIT"
  head "https://github.com/$repo.git", branch: "main"

  # The tree-sitter grammars are C: cc builds them, cargo drives it.
  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match "jack #{version}", shell_output("#{bin}/jack --version")
  end
end
FORMULA
    exit 0
fi

version=${1:?usage: render-formula.sh <version> <sums directory> | --source <version>}
sums=${2:?usage: render-formula.sh <version> <sums directory> | --source <version>}

# The four a formula can install, each named below where it is used. The musl
# tarball is published as well, for a distribution older than the runner's
# glibc, but Homebrew on Linux brings its own and wants the gnu one.
#
# A target whose tarball is not in the release is left out rather than fatal:
# one runner going missing should still produce a formula that installs on
# every platform that did build. Only an empty release is an error.
have() { [ -f "$sums/jack-$version-$1.tar.gz.sha256" ]; }

# Print the `on_arm`/`on_intel` block for one target, or a comment saying why
# there isn't one. $1 target, $2 `arm` or `intel`, $3 leading spaces.
entry() {
  local file="$sums/jack-$version-$1.tar.gz.sha256"
  if ! have "$1"; then
    printf '%s# No %s tarball in v%s.\n' "$3" "$1" "$version"
    return 0
  fi
  # `shasum -a 256` writes "<hash>  <name>"; the hash is all we want.
  printf '%son_%s do\n' "$3" "$2"
  printf '%s  url "https://github.com/%s/releases/download/v%s/jack-%s-%s.tar.gz"\n' \
    "$3" "$repo" "$version" "$version" "$1"
  printf '%s  sha256 "%s"\n' "$3" "$(cut -d' ' -f1 "$file")"
  printf '%send\n' "$3"
}

mac_arm=$(entry aarch64-apple-darwin arm "    ")
mac_intel=$(entry x86_64-apple-darwin intel "    ")
linux_arm=$(entry aarch64-unknown-linux-gnu arm "    ")
linux_intel=$(entry x86_64-unknown-linux-gnu intel "    ")

if ! have aarch64-apple-darwin && ! have x86_64-apple-darwin &&
   ! have aarch64-unknown-linux-gnu && ! have x86_64-unknown-linux-gnu; then
  echo "no tarballs for v$version in $sums - nothing to install" >&2
  exit 1
fi

cat <<FORMULA
# Generated by packaging/homebrew/render-formula.sh - do not edit by hand.
class Jack < Formula
  desc "Terminal text editor with tree-sitter highlighting and vim keys"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
$mac_arm
$mac_intel
  end

  on_linux do
$linux_arm
$linux_intel
  end

  def install
    bin.install "jack"
    # The icon, the desktop entry and the two scripts that install them: a
    # windowed editor wants a launcher entry as well as a binary, and a
    # bottled install has nowhere else to get them from.
    pkgshare.install "packaging/icon", "packaging/jack.desktop", "packaging/linux", "packaging/macos"
  end

  test do
    assert_match "jack #{version}", shell_output("#{bin}/jack --version")
  end
end
FORMULA
