#!/usr/bin/env bash
# Print the Homebrew formula for a released version, with the checksums of the
# tarballs that release actually contains.
#
# Usage: render-formula.sh <version> <directory of .sha256 files>
#
# The release workflow runs this and attaches the result to the release, so
# updating the tap is copying one file into it. Run it by hand the same way:
#   gh release download v0.1.0 --pattern '*.sha256' --dir sums
#   ./packaging/homebrew/render-formula.sh 0.1.0 sums > ../homebrew-tap/Formula/jack.rb
set -euo pipefail

version=${1:?usage: render-formula.sh <version> <sums directory>}
sums=${2:?usage: render-formula.sh <version> <sums directory>}
repo=${JACK_REPO:-rgsoda/jack-editor}

# The four a formula can install, each named below where it is used. The musl
# tarball is published as well, for a distribution older than the runner's
# glibc, but Homebrew on Linux brings its own and wants the gnu one.
sum_for() {
  local file="$sums/jack-$version-$1.tar.gz.sha256"
  if [ ! -f "$file" ]; then
    echo "missing checksum: $file" >&2
    exit 1
  fi
  # `shasum -a 256` writes "<hash>  <name>"; the hash is all we want.
  cut -d' ' -f1 "$file"
}

url_for() {
  echo "https://github.com/$repo/releases/download/v$version/jack-$version-$1.tar.gz"
}

mac_arm_url=$(url_for aarch64-apple-darwin)
mac_arm_sha=$(sum_for aarch64-apple-darwin)
mac_intel_url=$(url_for x86_64-apple-darwin)
mac_intel_sha=$(sum_for x86_64-apple-darwin)
linux_arm_url=$(url_for aarch64-unknown-linux-gnu)
linux_arm_sha=$(sum_for aarch64-unknown-linux-gnu)
linux_intel_url=$(url_for x86_64-unknown-linux-gnu)
linux_intel_sha=$(sum_for x86_64-unknown-linux-gnu)

cat <<FORMULA
# Generated by packaging/homebrew/render-formula.sh - do not edit by hand.
class Jack < Formula
  desc "Terminal text editor with tree-sitter highlighting and vim keys"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$mac_arm_url"
      sha256 "$mac_arm_sha"
    end
    on_intel do
      url "$mac_intel_url"
      sha256 "$mac_intel_sha"
    end
  end

  on_linux do
    on_arm do
      url "$linux_arm_url"
      sha256 "$linux_arm_sha"
    end
    on_intel do
      url "$linux_intel_url"
      sha256 "$linux_intel_sha"
    end
  end

  def install
    bin.install "jack"
  end

  test do
    assert_match "jack #{version}", shell_output("#{bin}/jack --version")
  end
end
FORMULA
