//! The tinted-theming scheme library, as themes.
//!
//! A base16 scheme is sixteen colours and a name, and there are hundreds of
//! them. What sixteen colours mean to an editor is one question, answered once
//! in `themes/base16-template.toml`; this module puts the two together, which
//! is a string replace and a parse.
//!
//! The palettes are embedded rather than read from disk, so a theme works on a
//! machine with nothing installed on it, and they are parsed only when
//! something asks - a session that never changes theme never looks at them.

use crate::theme::Theme;
use anyhow::{Context, Result};
use std::collections::HashMap;

/// The palettes: generated by `themes/import-base16.py`, MIT, and the licence
/// is beside them.
const SCHEMES: &str = include_str!("../themes/base16.toml");

/// What the sixteen mean. Written by hand, and the only file to edit when a
/// colour lands in the wrong place.
const TEMPLATE: &str = include_str!("../themes/base16-template.toml");

/// One scheme: what to call it, who chose it, and whether it is meant for a
/// light room or a dark one.
pub struct Scheme {
    pub slug: String,
    pub name: String,
    pub author: String,
    pub variant: String,
    palette: Vec<String>,
}

impl Scheme {
    /// Who chose these sixteen colours, ready to put after the name - empty
    /// when the scheme does not say. An email or a URL in the author field
    /// is dropped: it is a credit, not a directory entry.
    pub fn credit(&self) -> String {
        let who = self.author.split(['(', '<']).next().unwrap_or("").trim();
        match who.is_empty() {
            true => String::new(),
            false => format!(" by {who}"),
        }
    }

    /// The scheme as a theme, by putting its sixteen colours through the
    /// template. Layered over the built-in theme by the caller, so a key the
    /// template forgets still has something behind it.
    pub fn theme(&self) -> Result<Theme> {
        let mut text = TEMPLATE.to_string();
        for (index, colour) in self.palette.iter().enumerate() {
            text = text.replace(&format!("$base{index:02X}"), colour);
        }
        Theme::parse(&text).with_context(|| format!("building the {} theme", self.slug))
    }
}

#[derive(serde::Deserialize)]
struct Entry {
    name: String,
    variant: String,
    #[serde(default)]
    author: String,
    palette: Vec<String>,
}

/// Every scheme, by slug. Parsed on each call: it is a hundred kilobytes of
/// TOML and the callers are a `:set theme=` and a picker being opened, neither
/// of which happens in a loop.
pub fn schemes() -> Vec<Scheme> {
    let entries: HashMap<String, Entry> = match toml::from_str(SCHEMES) {
        Ok(entries) => entries,
        // Generated and tested; a failure here is a broken build, not
        // something a running editor should die of.
        Err(_) => return Vec::new(),
    };
    let mut schemes: Vec<Scheme> = entries
        .into_iter()
        .filter(|(_, entry)| entry.palette.len() == 16)
        .map(|(slug, entry)| Scheme {
            slug,
            name: entry.name,
            author: entry.author,
            variant: entry.variant,
            palette: entry.palette,
        })
        .collect();
    schemes.sort_by(|a, b| a.slug.cmp(&b.slug));
    schemes
}

/// One scheme by slug, or nothing if no such scheme.
pub fn scheme(slug: &str) -> Option<Scheme> {
    schemes().into_iter().find(|scheme| scheme.slug == slug)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_library_is_there_and_every_scheme_has_sixteen_colours() {
        let schemes = schemes();
        assert!(schemes.len() > 300, "{} schemes", schemes.len());
        assert!(schemes.iter().all(|s| s.palette.len() == 16));
        assert!(schemes.iter().all(|s| s.palette.iter().all(|c| c.starts_with('#') && c.len() == 7)));
    }

    /// The template is only checked by using it, so use it on all of them.
    /// A key with a typo in its colour would otherwise sit there until
    /// somebody picked the one scheme that reached it.
    #[test]
    fn every_scheme_builds_a_theme() {
        for scheme in schemes() {
            let theme = scheme.theme();
            assert!(theme.is_ok(), "{}: {:?}", scheme.slug, theme.err());
        }
    }

    /// Nothing in the template should be left holding a placeholder: a
    /// `$base10` typo parses as a colour name and fails much later.
    #[test]
    fn the_template_spends_all_of_its_placeholders() {
        let scheme = scheme("gruvbox-dark-hard").expect("a scheme everyone has heard of");
        let mut text = TEMPLATE.to_string();
        for (index, colour) in scheme.palette.iter().enumerate() {
            text = text.replace(&format!("$base{index:02X}"), colour);
        }
        assert!(!text.contains("$base"), "left over: {text}");
    }

    /// The whole point of the template: a scheme has to come out with the
    /// editor's own furniture coloured, not just the syntax.
    #[test]
    fn a_built_scheme_covers_the_editor_and_not_only_the_grammar() {
        let theme = scheme("solarized-light").expect("solarized").theme().unwrap();
        for key in ["ui.statusline", "ui.cursorline", "ui.picker", "ui.dim", "keyword", "string"] {
            assert!(theme.has(key), "{key} went missing");
        }
    }

    /// The picker builds one of these on every keypress, so it is worth
    /// knowing what one costs. Most of it is parsing the hundred kilobytes
    /// of palettes, which is done on demand rather than at startup.
    #[test]
    fn building_one_is_quick_enough_to_do_on_every_key() {
        let started = std::time::Instant::now();
        for _ in 0..10 {
            scheme("nord").expect("nord").theme().unwrap();
        }
        let each = started.elapsed() / 10;
        println!("a theme costs {each:?}");
        assert!(each < crate::budget::budget(20), "{each:?} for one theme");
    }

    #[test]
    fn a_credit_is_a_name_rather_than_a_directory_entry() {
        let scheme = scheme("gruvbox-dark-hard").expect("gruvbox");
        assert_eq!(scheme.credit(), " by Dawid Kurek");
        assert!(!scheme.credit().contains('@'), "no email in the status line");
    }

    #[test]
    fn both_kinds_of_room_are_catered_for() {
        let schemes = schemes();
        assert!(schemes.iter().any(|s| s.variant == "light"));
        assert!(schemes.iter().any(|s| s.variant == "dark"));
    }
}
